import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fff4f4",
        "surface-bright": "#fff4f4",
        "surface-dim": "#ffc6ce",
        "surface-variant": "#ffd2d7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffecee",
        "surface-container": "#ffe1e4",
        "surface-container-high": "#ffd9de",
        "surface-container-highest": "#ffd2d7",
        "background": "#fff4f4",
        "on-background": "#4d212a",
        "on-surface": "#4d212a",
        "on-surface-variant": "#814c55",
        "outline": "#a06770",
        "outline-variant": "#dd9ca6",
        "inverse-surface": "#24020a",
        "inverse-on-surface": "#cb8c96",
        "surface-tint": "#ba001c",
        "primary": "#ba001c",
        "primary-dim": "#a40017",
        "primary-container": "#ff7670",
        "primary-fixed": "#ff7670",
        "primary-fixed-dim": "#ff5a57",
        "on-primary": "#ffefee",
        "on-primary-container": "#4e0006",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#600009",
        "inverse-primary": "#ff5352",
        "secondary": "#0b50d5",
        "secondary-dim": "#0044bf",
        "secondary-container": "#c4d0ff",
        "secondary-fixed": "#c4d0ff",
        "secondary-fixed-dim": "#b1c2ff",
        "on-secondary": "#f1f2ff",
        "on-secondary-container": "#003dac",
        "on-secondary-fixed": "#002c83",
        "on-secondary-fixed-variant": "#0045c1",
        "tertiary": "#6c5a00",
        "tertiary-dim": "#5e4e00",
        "tertiary-container": "#ffd709",
        "tertiary-fixed": "#ffd709",
        "tertiary-fixed-dim": "#efc900",
        "on-tertiary": "#fff2cd",
        "on-tertiary-container": "#5b4b00",
        "on-tertiary-fixed": "#453900",
        "on-tertiary-fixed-variant": "#665500",
        "error": "#b02500",
        "error-dim": "#b92902",
        "error-container": "#f95630",
        "on-error": "#ffefec",
        "on-error-container": "#520c00",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        editorial: "0px 20px 40px rgba(77, 33, 42, 0.06)",
        "editorial-sm": "0px 10px 30px rgba(77, 33, 42, 0.04)",
      },
      keyframes: {
        moveRider: {
          "0%": { offsetDistance: "0%" },
          "100%": { offsetDistance: "100%" },
        },
        slideIn: {
          "0%": { transform: "translateX(-20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0)", opacity: "0" },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        moveRider: "moveRider 10s linear infinite",
        slideIn: "slideIn 0.5s ease-out",
        slideUp: "slideUp 0.5s ease-out",
        fadeIn: "fadeIn 0.5s ease-out",
        scaleIn: "scaleIn 0.5s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
