ALTER TABLE public.vendors 
ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 4.0,
ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS type TEXT,
ADD COLUMN IF NOT EXISTS delivery_charge NUMERIC DEFAULT 0;

NOTIFY pgrst, 'reload schema';
